### ISSUE TITLE
Manual Install

### ISSUE THREAD

**Issue by andrenjdev** [makomori/Sharaku#1]
I've a problem to install your library.
I can't use: "use_frameworks!" in my project, can I install it manually?
Thanks a lot!
Great Work!

**Comment by makomori** [comment]
@andre1720 Thanks for your comment. I haven't tried manual install, but I'm gonna do that and write how to install manually later. Please wait for a while.

**Comment by makomori** [comment]
@andre1720 Hi. I've written how to install Sharaku manually in readme. Please try like that. And if you don't success, please let me know. Thank you!

**Comment by andrenjdev** [comment]
That's great!  It works :)
Thanks a lot!
